accounts/urls.py
"""Account URL Configuration"""


from django.urls import path
from accounts.views import (
    register_view,
    login_view,
    logout_view,
    )


urlpatterns = [
    path('signup/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

referral_network/urls.py
"""referral_network URL Configuration"""

from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('referrals/', include('referrals.urls')),
    path('', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

referrals/urls.py
"""Referral URL Configuration"""


from django.urls import path
from referrals.views import referral_view


urlpatterns = [
    path('', referral_view, name='referrals'),
]

profiles/models.py
"""Post Models

A model is the single, definitive source of information about your data.
It contains the essential fields and behaviors of the data you’re storing.
Generally, each model maps to a single database table.
"""

from django.db import models
from django.contrib.auth.models import User


def upload_avatar(instance, filename):
    """Returns path to avatar in media directory."""
    return '/'.join(['profiles', str(instance.user.id), filename])


class Profile(models.Model):
    """User profile.

    Using one-to-one communication with a user model.
    Stores additional user information.
    Stores only current avatar.
    """
    BLANK = ''
    STUDENT = 'ST'
    PROGRAMMER = 'PR'
    ENGINEER = 'EN'
    ML_ENGINEER = 'ML'
    OTHER = 'OR'
    PROFESSION_CHOICES = [
        (BLANK, 'Your profession?'),
        (STUDENT, 'Student'),
        (PROGRAMMER, 'Programmer'),
        (ENGINEER, 'Engineer'),
        (ML_ENGINEER, 'Machine Learning engineer'),
        (OTHER, 'Other'),
    ]
    profession = models.CharField(
        max_length=2,
        choices=PROFESSION_CHOICES,
        null=True,
        blank=True
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    avatar = models.ImageField(upload_to=upload_avatar,
                               null=False, blank=False,
                               default='default_avatar.png',
                               )
    bio = models.CharField(max_length=500, blank=True)
    ref_code = models.TextField(max_length=20, null=False, unique=True)

    def get_absolute_url(self):
        return "/profiles/%i/" % self.id

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ["-timestamp"]


def upload_profile_images(instance, filename):
    """Returns path to profile image in media directory."""
    return '/'.join(['profiles', str(instance.profile.user.id), filename])


class ProfileImage(models.Model):
    """Stores not only current avatar but all added avatars."""
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="profile_images")
    image = models.ImageField(upload_to=upload_profile_images,
                              null=True, blank=True,
                              )

referrals/models.py
"""Referrals Models

A model is the single, definitive source of information about your data.
It contains the essential fields and behaviors of the data you’re storing.
Generally, each model maps to a single database table.
"""

from django.db import models
from django.contrib.auth.models import User


class Referral(models.Model):
    """Stores referrers and referrals.

    Every user can be a referrer multiple times.
    Referral - unique field. Every user can be referral only once.
    """
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    referrer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_referrers')
    referral = models.OneToOneField(User, on_delete=models.CASCADE)

profiles/forms.py
"""Profile Forms

Form class describes a form and determines how it works and appears.
In a similar way that a model class’s fields map to database fields,
a form class’s fields map to HTML form <input> elements.
"""

from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={'multiple': True}))

    class Meta:
        model = Profile
        fields = ('profession', 'bio', 'image')
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 4,
                                         'wrap': 'hard',
                                         'placeholder': 'Tell people something interesting about yourself!'}),
        }

referrals/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required()
def referral_view(request):
    """Displays links to all referral of current user and their amount."""
    ref_list = request.user.user_referrers.all()
    ref_count = ref_list.count()
    context = {
        'ref_count': ref_count,
        'ref_list': ref_list,
    }
    return render(request, "referrals.html", context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Referral Network</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">

  <!-- Favicon -->
  <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Reset CSS File -->
  <link  rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">

    <!-- Bootstrap Stylesheets -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Main Stylesheet File -->
  <link  rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


</head>
<body>

<div class="container-fluid bg-blue">
        <div class="container bg-blue">
            <nav class="navbar navbar-expand ">

              <div class="collapse navbar-collapse" id="navbarNav">
              {% if user.is_authenticated %}
                  <ul class="navbar-nav">
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'home'%}">My profile</a>
                     </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'referrals'%}">Referrals</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'list'%}">Profiles</a>
                     </li>
                  </ul>
                  <ul class="navbar-nav ml-auto">
                      <li class="nav-item">
                        <a class="nav-link disabled username">{{ user.username }}</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout'%}">Logout</a>
                      </li>
                 </ul>
                  {% else %}
                       <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register'%}">Register</a>
                            </li>
                           <li class="nav-item">
                                <a class="nav-link" href="{% url 'login'%}">Login</a>
                            </li>
                        </ul>
                  {% endif %}
              </div>
            </nav>
        </div>
    </div>

{% block content %}{% endblock content %}


</body>
</html>

templates/home_view.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container">

    <div class="row">
        <div class="col-12 ">
            <div class="profile-form-container">
                <div class="profile-form-title">
                    <span>Update your profile</span>
                </div>
                <form class='profile-form ' method='POST' enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{form.bio}}
                    <label class="label_img" for="id_image">Add photos</label>
                    {{form.image}}
                    {{form.profession}}
                    <input type='submit' id="saveButton" value="Update profile">
                </form>

            </div>
        </div>
    </div>

    <div class="profile-looks-header"><p>Your profile looks like:</p></div>
    {% include 'profile_component.html' %}

</div>

{% endblock content %}

templates/login.html
{% extends "base.html" %}

{% block content %}
        <div class="container account-forms-container">
          <div class="row justify-content-center">
                {% if not user.is_authenticated %}
                  <div class="col-auto">
                        <span>Already have an Account?</span>
                      <form class='log-in-form ' method='POST' autocomplete="off">
                          {% csrf_token %}
                          {{ log_in_form|safe }}
                          <input type='submit' id="log-in-button" value="Log in">
                      </form>
                      {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                      {% endif %}
                  </div>
                {% else %}
                    <p>You are already logged in.</p>
                {% endif %}
            </div>
        </div>

{% endblock content %}

templates/login_register.html
{% extends "base.html" %}



{% block content %}
        <div class="container account-forms-container">
          <div class="row justify-content-around">
                {% if not user.is_authenticated %}
                  <div class="col-auto">
                        <span>Already have an Account?</span>
                      <form class='log-in-form ' method='POST' autocomplete="off">
                          {% csrf_token %}
                          {{ log_in_form|safe }}
                          <input type='submit' id="log-in-button" value="Log in">
                      </form>
                  </div>
                {% endif %}

                  <div class="col-auto ">
                        <span>Create new Account</span>
                      <form class="register-form" method="POST">
                          {% csrf_token %}
                          {% for field in sign_up_form %}
                              <div class=" ">
                                  <div>{{ field }}</div>
                                  {% if field.errors %}
                                      {% for error in field.errors %}
                                          <div>
                                              {{ error }}
                                          </div>
                                      {% endfor %}
                                  {% endif %}
                              </div>
                          {% endfor %}
                          <input type="submit" id="sign-up-button" value="Sign Up">
                      </form>
                  </div>
            </div>
        </div>

{% endblock content %}

templates/my_profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-12 ">
            <div class="profile-form-container">
                <div class="profile-form-title">
                    <span>Update your profile</span>
                </div>
                <form class='profile-form ' method='POST' enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{form.bio}}
                    <label class="label_img" for="id_image">Add photos</label>
                    {{form.image}}
                    {{form.profession}}
                    <input type='submit' id="saveButton" value="Update profile">
                </form>
                {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="profile-looks-header"><p>Your profile looks like:</p></div>
    {% include 'profile_component.html' %}

</div>

{% endblock content %}

templates/profile_component.html
<div class="profile-detail-container">
    <div class="row justify-content-center">
        <div class='col-auto padding-reset  profile-detail-content'>
            <div class="row justify-content-start profile-preview-txt">
              <div class="col-auto author">{{ profile.user.username }}</div>
            </div>
            <div class="row justify-content-start profile-info">
                <div class="col-12"><span>Email:</span> {{ profile.user.email}}</div>
                {% if  profile.profession %}
                    <div class="col-12"><span>Profession:</span> {{ profile.get_profession_display }}</div>
                {% endif %}
                {% if  profile.bio %}
                    <div class="col-12 "><p><span>About me:</span> {{ profile.bio|linebreaks }}</p></div>
                {% endif %}
             </div>
                <hr>
                <p>Avatar:</p> <br>
                <p class="p_img"><img src='http://127.0.0.1:8000/media/{{ profile.avatar }}' class='img-responsive'/></p>

            {% if images %}
                <p>Previous avatars:</p>
            {% endif %}
            {% for img in images %}
                <hr>
                <p class="p_img"><img src='http://127.0.0.1:8000/media/{{ img.image }}' class='img-responsive'/></p>
            {% endfor %}
        </div>
    </div>
</div>

templates/profile_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        {% include 'profile_component.html' %}
    </div>
{% endblock content %}
</body>
</html>

templates/profile_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">

{% for obj in object_list %}

    <div class="row justify-content-center">
      <div class="col-auto ">
          <div class="profile-preview-block">
              <div class="row justify-content-between profile-preview-txt">
                  <div class="col-auto author">{{ obj.user.username }}</div>
                  {% if  obj.profession %}
                  <div class="col-auto author">{{ obj.get_profession_display }}</div>
                  {%  endif %}
              </div>
              <div class="profile-preview-txt">{{ obj.bio|linebreaks|truncatechars:320 }}</div>
              <a href='{{ obj.get_absolute_url }}'><img src='http://127.0.0.1:8000/media/{{ obj.avatar }}' class='profile-picture' /></a>

          </div>
      </div>
    </div>

{% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

</div>


{% endblock content %}

templates/referrals.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">

    <div class="row justify-content-center">
        <div class="col-auto ">
            <div class="invite-block">
                <span>Invite your friends! </span>
                <p>You can copy default invitation or edit it.</p>
<textarea class="invite-text" rows="6" cols="38">Hi!
Start using the best social network in the world!
Join via this link:
http://127.0.0.1:8000/account/signup?ref={{ user.profile.ref_code }}
and become my referral :))
</textarea>
                <button class="copy-invite">Copy invitation</button>
            </div>

        <div class="referral-list">
            {% if not ref_count %}
            <p>You don`t have referrals yet. Invite your friends!</p>
            {% else %}
            <p>You have <b>{{ ref_count }}</b> active referral(s) joined via your referral link:</p>
                <ul>
                {% for ref in ref_list %}
                        <li><a href="http://127.0.0.1:8000/profiles/{{ ref.referral.profile.id }}">{{ ref.referral }}</a></li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>

        </div>
    </div>

</div>

<script src="{% static 'js/copy_invite.js' %}"></script>

{% endblock content %}

templates/register.html
{% extends "base.html" %}

{% block content %}
        <div class="container account-forms-container">
          <div class="row justify-content-center">

                  <div class="col-auto ">
                        <span>Create new Account</span>
                      <form class="register-form" method="POST">
                          {% csrf_token %}
                          {% for field in sign_up_form %}
                              <div class=" ">
                                  <div>{{ field }}</div>
                                  {% if field.errors %}
                                      {% for error in field.errors %}
                                          <div>
                                              {{ error }}
                                          </div>
                                      {% endfor %}
                                  {% endif %}
                              </div>
                          {% endfor %}
                          <input type="submit" id="sign-up-button" value="Sign Up">
                      </form>
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                  </div>
            </div>
        </div>

{% endblock content %}

templates/your_profile.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container">

    <div class="row">
        <div class="col-12 ">
            <div class="post-form-container">
                <div class="post-form-title">
                    <span>Update your profile</span>
                </div>
                <form class='post-form ' method='POST' enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{form|safe}}
                    <label class="label_img" for="id_image">Photo</label>
                    <input type='submit' id="saveButton" value="Post">
                </form>

            </div>
        </div>
    </div>

</div>

{% endblock content %}